BetterLights = BetterLights or {}

local BL = BetterLights

BL.NET_EVENT_MESSAGE = "BetterLights_Event"
BL.NET_FLASHLIGHT_CLIENT_ENABLE = "BetterLights_FlashlightClientEnable"
BL.NET_FLASHLIGHT_SOUND = "BetterLights_FlashlightSound"
BL.NET_SET_SERVER_BOOL = "BetterLights_SetServerBool"

BL.NET_MUZZLE_FLASH = 1
BL.NET_BULLET_IMPACT = 2
BL.NET_STRIDER_MUZZLE_FLASH = 3
BL.NET_STRIDER_BULLET_IMPACT = 4
BL.NET_HUNTER_CHOPPER_MUZZLE_FLASH = 5
BL.NET_HUNTER_CHOPPER_BULLET_IMPACT = 6
BL.NET_STUNSTICK_IMPACT = 7
