name: Feature Request
description: Suggest a new feature or enhancement for BetterLights
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! We appreciate your feedback.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New light effect for existing entity/weapon
        - New entity/weapon support
        - Settings/configuration option
        - Performance improvement
        - Visual quality improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the scenario where this feature would be useful.
      placeholder: This would be useful when...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought of...
    validations:
      required: false

  - type: textarea
    id: reference
    attributes:
      label: Reference/Examples
      description: |
        If applicable, provide links to reference images, videos, or other mods that demonstrate similar functionality.
      placeholder: Links or descriptions of references...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request.
      placeholder: Any other details...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate request
          required: true
